name: Docker build & push

on: push

env:
  REGISTRY: ghcr.io
  SUBPATH: theverygaming
  IMAGE_NAME: sondehub-alert

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: registry login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.SUBPATH }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
